USE [ERP]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[hrm_OTP](
    [OTPId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [EmployeeId] UNIQUEIDENTIFIER NOT NULL,
    [OTP] NVARCHAR(6) NOT NULL,
    [CreatedDateTime] DATETIME NOT NULL DEFAULT GETDATE(),
    [IsVerified] BIT NOT NULL DEFAULT 0,
 CONSTRAINT [PK_dbo.hrm_OTP] PRIMARY KEY CLUSTERED 
(
    [OTPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, 
      IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
