USE [ERP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[rq_Request_Group](
	[RequestGroupId] [uniqueidentifier] NOT NULL DEFAULT (NEWSEQUENTIALID()),
	[Active] [bit] NOT NULL DEFAULT ((1)),
 CONSTRAINT [PK_rq_Request_Group] PRIMARY KEY CLUSTERED
(
	[RequestGroupId] ASC
)WITH (
	PAD_INDEX = OFF, 
	STATISTICS_NORECOMPUTE = OFF, 
	IGNORE_DUP_KEY = OFF, 
	ALLOW_ROW_LOCKS = ON
) ON [PRIMARY]
) ON [PRIMARY]
GO